name: Python Syntax Check

on: [push, pull_request]

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Linter
        run: pip install ruff

      - name: Check for Syntax Errors
        # This will fail the build if it finds any syntax errors
        run: ruff check --format=github ./src
